theme: minima
title: Damoon Shahhosseini
baseurl: "/w"
url: "https://damoonsh.github.io"

plugins:
  - jekyll-mermaid

# Automatically apply layout: post to every post
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
